runtime: java11
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.8
  min_instances: 1
  max_instances: 10
  max_pending_latency: 1s
  max_concurrent_requests: 50